baseURL = "https://Acetyl12.github.io/" 
title   = "Blog Lập Trình Mạng"
theme   = "blist"
languageCode = "vi"

[pagination]
  pagerSize = 10


[params]
  enableSearch = true              # bật icon & index tìm kiếm
  darkModeToggle = true          # (tuỳ chọn) bật nút Dark/Light
  ascentColor = "bg-blue-200"    # (tuỳ chọn) đổi màu nhấn, theo Tailwind
  # logo = "/images/logo.png"      # (tuỳ chọn) logo thay vì text
  social = [ {name="github", url="https://github.com/Acetyl12"} ]

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url  = "/portfolio/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    url  = "/tags/"
    weight = 5


[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]