name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Tránh 2 lần deploy chồng nhau
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node (for PostCSS/Tailwind)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install theme deps (Blist)
        run: |
          if [ -f package.json ]; then
            npm ci || npm i
          fi
          npm i -g postcss-cli
          # Cập nhật caniuse-lite để tránh cảnh báo
          npx update-browserslist-db@latest || true

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          # Khóa phiên bản bạn đang dùng local cho đồng nhất (0.151.0 OK)
          hugo-version: "0.151.0"
          extended: true

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Compute baseURL
        id: base
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          echo "BASE_URL=https://${OWNER}.github.io/${REPO}/" >> $GITHUB_OUTPUT

      - name: Build
        env:
          BASE_URL: ${{ steps.base.outputs.BASE_URL }}
        run: |
          hugo --cleanDestinationDir --gc --minify --baseURL "${BASE_URL}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
